version: '3'
services: 
  weatherapplication:
    build: 
     context: .
     dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/go/src/app
 # tests:
 #   build: 
 #    context: .
 #    dockerfile: Dockerfile.dev
 #   volumes:
 #     - .:/go/src/app
